// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/manager/all": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "查询所有的用户体温信息",
                "responses": {
                    "200": {
                        "description": "{\"code\": 200,\"msg\": \"success\",\"data\": \"normal_count: \"2\",\"normals\": [{\"name\": \"xiaoming\",\"date\": \"2021-08-19\"},{\"name\": \"xiaohong\",\"date\": \"2021-08-25\"}],\"abnormal_count\": \"1\",\"abnormals\": [{\"name\": \"xiaoli\",\"date\": \"2021-08-12\"}]}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/manager/daily/{date}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "根据日期查询当天的用户体温信息",
                "responses": {
                    "200": {
                        "description": "{\"code\": 200,\"msg\": \"success\",\"data\": \"normal_count: \"2\",\"normal_names\": [\"xiaoming\",\"xiaohong\"],\"abnormal_count\": \"1\",\"abnormal_names\": [\"xiaoli\"]}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/manager/moon/{date}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "根据年月查询当月的用户体温信息",
                "responses": {
                    "200": {
                        "description": "{\"code\": 200,\"msg\": \"success\",\"data\": \"normal_count: \"2\",\"normals\": [{\"name\": \"xiaoming\",\"date\": \"2021-08-19\"},{\"name\": \"xiaohong\",\"date\": \"2021-08-25\"}],\"abnormal_count\": \"1\",\"abnormals\": [{\"name\": \"xiaoli\",\"date\": \"2021-08-12\"}]}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/user/daily": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "用户上传体温",
                "responses": {
                    "200": {
                        "description": "{\"code\": 200,\"msg\": \"success\",\"data\": null}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/user/stats": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "用户获取自己近期体温情况",
                "responses": {
                    "200": {
                        "description": "{\"code\": 200,\"msg\": \"success\",\"data\": \"no_abnormal: true,\"daily_stats\": [\"date\": \"2021-08-30\",\"normal\": true]\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "47.100.236.6:3305",
	BasePath:    "\"/api\"",
	Schemes:     []string{},
	Title:       "TemperatureBackend API",
	Description: "author github@cjdjczym.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
